/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import entidade.aluno;
import java.awt.image.BufferedImage;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloDao.DaoAluno;
import modeloDao.ModeloTabela;
import utilitarios.ArduinoSerial;
import utilitarios.ConectaBanco;
import utilitarios.ManipularImagem;

/**
 *
 * @author Znoque
 */
public class TelaPesquisa extends javax.swing.JFrame {
    ConectaBanco conexao = new ConectaBanco();
    aluno mod = new aluno();
    DaoAluno control = new DaoAluno();
    BufferedImage imagem;
    String mat;
    boolean a = false;
    int flag = 0;
    /**
     * Creates new form TelaConsulta
     */
    public TelaPesquisa() {
        initComponents();
        jBoxPorta.setSelectedIndex(3);
        //preencherTabela("select matricula, nome, curso, turma, turno, serie, dia, idcartao, imagem from alunos order by nome");
    }

    public void cartao(){
        ArduinoSerial arduino = new ArduinoSerial(String.valueOf(jBoxPorta.getSelectedItem()));
        arduino.initialize();
        flag=0;
        if(a==true){
            while(flag<=40000){
                System.out.println(flag);
                System.out.println(arduino.read());
                lblId.setText(arduino.read());
                flag++;
            }
        }else{
            arduino.close();
        }
        arduino.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jBoxFiltro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnId = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jBoxPorta = new javax.swing.JComboBox<>();
        btnCOM = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        jBoxFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Matrícula", "Cartão" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cartão:");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnId.setText("ID");
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Porta Arduino:");

        jBoxPorta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBoxPorta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10" }));

        btnCOM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCOM.setText("Set");
        btnCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCOM)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnId)
                    .addComponent(jLabel9)
                    .addComponent(jBoxPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCOM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Pesquisar:");

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelecionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(680, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        mod.setFiltro(String.valueOf(jBoxFiltro.getSelectedItem()));
        String filtro = mod.getFiltro();
        System.out.println(filtro);
        switch(filtro){
            case "Nome":
                preencherTabela("select matricula, nome, curso, turma, turno, serie, dia, idcartao, imagem from alunos where nome like'%"+txtPesquisa.getText()+"%' order by nome");
                break;
            case "Matrícula":
                preencherTabela("select matricula, nome, curso, turma, turno, serie, dia, idcartao, imagem from alunos where matricula like'%"+txtPesquisa.getText()+"%' order by nome");
                break;
            case "Cartão":
                preencherTabela("select matricula, nome, curso, turma, turno, serie, dia, idcartao, imagem from alunos where idcartao like'%"+txtPesquisa.getText()+"%' order by nome");
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Não foi possivel encontrar esse filtro");
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
        // TODO add your handling code here:
        a = true;
        cartao();
    }//GEN-LAST:event_btnIdActionPerformed

    private void btnCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOMActionPerformed
        // TODO add your handling code here:
        //Verificando e setando o JBOXPorta
        if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM1")){
            jBoxPorta.setSelectedIndex(0);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM2")){
            jBoxPorta.setSelectedIndex(1);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM3")){
            jBoxPorta.setSelectedIndex(2);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM4")){
            jBoxPorta.setSelectedIndex(3);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM5")){
            jBoxPorta.setSelectedIndex(4);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM6")){
            jBoxPorta.setSelectedIndex(5);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM7")){
            jBoxPorta.setSelectedIndex(6);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM8")){
            jBoxPorta.setSelectedIndex(7);
        }else if(String.valueOf(jBoxPorta.getSelectedItem()).equals("COM9")){
            jBoxPorta.setSelectedIndex(8);
        }else{
            jBoxPorta.setSelectedIndex(9);
        }
    }//GEN-LAST:event_btnCOMActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked
        // TODO add your handling code here:
        String pesquisa = ""+jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 0);
        conexao.conectar();
        conexao.executaSql("select * from alunos where matricula='"+pesquisa+"'");
        try {
            conexao.rs.first();
            mat = conexao.rs.getString("matricula");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados\nErro: "+ex);
        } finally {
            conexao.desconectar();
        }
    }//GEN-LAST:event_jTableAlunoMouseClicked

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        TelaResultado resultado = new TelaResultado(mat);
        resultado.setVisible(true);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    public void limparTela(){
        lblId.setText("");
        txtPesquisa.setText("");
        jBoxPorta.setSelectedIndex(3);
        mat = "";
        conexao.desconectar();
    }
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Matricula", "Nome", "Curso", "Turma", "Turno", "Série", "Id Cartão", "Dia Almoço"};
        conexao.conectar();
        conexao.executaSql(Sql);
        try{
            PreparedStatement pst;
            conexao.rs.first();
            do{
                dados.add(new Object[]{conexao.rs.getInt("matricula"), conexao.rs.getString("nome"), conexao.rs.getString("curso"), conexao.rs.getString("turma"), conexao.rs.getString("turno"), conexao.rs.getString("serie"), conexao.rs.getString("idcartao"), conexao.rs.getString("dia")});
            }while(conexao.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher Tabela de Alunos\nAlunos não Encontrados\nErro: "+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableAluno.setModel(modelo);
        jTableAluno.getColumnModel().getColumn(0).setPreferredWidth(75);
        jTableAluno.getColumnModel().getColumn(0).setResizable(false);
        jTableAluno.getColumnModel().getColumn(1).setPreferredWidth(240);
        jTableAluno.getColumnModel().getColumn(1).setResizable(false);
        jTableAluno.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTableAluno.getColumnModel().getColumn(2).setResizable(false);
        jTableAluno.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableAluno.getColumnModel().getColumn(3).setResizable(false);
        jTableAluno.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableAluno.getColumnModel().getColumn(4).setResizable(false);
        jTableAluno.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableAluno.getColumnModel().getColumn(5).setResizable(false);
        jTableAluno.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableAluno.getColumnModel().getColumn(6).setResizable(false);
        jTableAluno.getColumnModel().getColumn(7).setPreferredWidth(90);
        jTableAluno.getColumnModel().getColumn(7).setResizable(false);
        jTableAluno.getTableHeader().setReorderingAllowed(false);
        jTableAluno.setAutoResizeMode(jTableAluno.AUTO_RESIZE_OFF);
        jTableAluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconectar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCOM;
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<String> jBoxFiltro;
    private javax.swing.JComboBox<String> jBoxPorta;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
